/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_actions_pcbatest_SerialPort */

#ifndef _Included_com_actions_pcbatest_SerialPort
#define _Included_com_actions_pcbatest_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_actions_pcbatest_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_actions_pcbatest_SerialPort_open
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
